baseURL = "https://ouro-boros.com/"
languageCode = "en-us"
theme = "tailwind-wall"

enableEmoji = true
enableRobotsTXT = true
canonifyURLs = true

disableKinds = ["section", "taxonomy", "taxonomyTerm", "robotsTXT"]

[params]
  title = "Ouro"
  description = "Boros"
  tagline = "Halloween Costume"
  useFaviconGenerator = false # https://www.favicon-generator.org/

  # whoami
  author = "DK"
  logo = "https://via.placeholder.com/512.png?text=DK"
  header = "Week In Memes"

  # service
  googleTagManager = "G-VZH95MYSJV"
  histats = ""
  cookieConsent = false

  # ads
  socialBar = ''''''
  banner300x250 = ''''''
  banner468x60 = ''''''
  banner728x90 = ''''''
  bannerFixed = ''''''
  bannerInArticle = ''''''
  popUnder = ''''''
  directLink = ''''''
  adsenseInit = '''<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7547725812395812" crossorigin="anonymous"></script>'''

[permalinks]
  post = "/:slug/"
  page = "/page/:slug/"

[menu]
  [[main]]
    identifier = "page"
    name = "Home"
    url = "/"
    weight = 1

  [[main]]
    identifier = "page"
    name = "DMCA"
    url = "/page/dmca/"
    weight = 2

  [[main]]
    identifier = "page"
    name = "Contact"
    url = "/page/contact/"
    weight = 3

  [[main]]
    identifier = "page"
    name = "Privacy Policy"
    url = "/page/privacy-policy/"
    weight = 4

  [[main]]
    identifier = "page"
    name = "Copyright"
    url = "/page/copyright/"
    weight = 5

[minify]
  minifyOutput = true

[outputs]
  home = ["RSS", "HTML", "JSON"]

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss"
    baseName = "x_feed"

[sitemap]
  changefreq = "monthly"
  filename = "x_sitemap.xml"
  priority = 0.7

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true